# Generated by Django 3.0.3 on 2020-03-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_identification_and_parentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=20)),
                ('breed', models.CharField(blank=True, max_length=20)),
                ('dam_no', models.CharField(blank=True, max_length=20)),
                ('sire_no', models.CharField(blank=True, max_length=20)),
                ('grand_dam', models.CharField(blank=True, max_length=20)),
                ('grand_sire', models.CharField(blank=True, max_length=20)),
                ('colitter_size_of_birth', models.IntegerField(blank=True, null=True)),
                ('color_and_marking', models.TextField(blank=True)),
                ('abnormalities', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='service_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sow_no', models.CharField(blank=True, max_length=20)),
                ('dos', models.DateField(blank=True, null=True)),
                ('dof', models.DateField(blank=True, null=True)),
                ('parity', models.IntegerField(blank=True, null=True)),
                ('born_male', models.IntegerField(blank=True, null=True)),
                ('born_female', models.IntegerField(blank=True, null=True)),
                ('born_total', models.IntegerField(blank=True, null=True)),
                ('litter_weight_birth', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('weaned_male', models.IntegerField(blank=True, null=True)),
                ('weaned_female', models.IntegerField(blank=True, null=True)),
                ('total_weaned', models.IntegerField(blank=True, null=True)),
                ('weaning_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('still_birth_abnormality', models.IntegerField(blank=True, null=True)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='qualification_boar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_fitness', models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Good', max_length=10)),
                ('date_of_training', models.DateField(blank=True, null=True)),
                ('period_of_training', models.IntegerField(blank=True, null=True)),
                ('training_score', models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Good', max_length=10)),
                ('seminal_characteristics', models.CharField(choices=[('Poor', 'Poor'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], default='Good', max_length=10)),
                ('suitability', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='nutrition_and_feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='health_parameter_vetexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('date_of_treatment', models.DateField(blank=True, null=True)),
                ('medication', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('postmortem', models.TextField(blank=True)),
                ('gip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='health_parameter_vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=50)),
                ('make', models.CharField(blank=True, max_length=20)),
                ('first_dose', models.DateField(blank=True, null=True)),
                ('booster_does', models.DateField(blank=True, null=True)),
                ('repeat', models.DateField(blank=True, null=True)),
                ('gip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='efficiency_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.DateField(blank=True, null=True)),
                ('weaning_age', models.IntegerField(blank=True, null=True)),
                ('weaning_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dos', models.DateField(blank=True, null=True)),
                ('doc', models.DateField(blank=True, null=True)),
                ('dosm', models.DateField(blank=True, null=True)),
                ('sexual_maturity_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_six', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weaning_eight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('conform_at_eight', models.TextField(blank=True)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='economics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_value', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('amount_realized', models.IntegerField(blank=True, null=True)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
        migrations.CreateModel(
            name='disposal_culling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('weight_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cause_death', models.TextField(blank=True)),
                ('date_death', models.DateField(blank=True, null=True)),
                ('gip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigdata.general_identification_and_parentage')),
            ],
        ),
    ]
